include:
  - ./auth_service/docker-compose.yml
  - ./chat_service/docker-compose.yml
  - ./matching_service/docker-compose.yml
  - ./notification_service/docker-compose.yml
  - ./selection_deck_service/docker-compose.yml
  - ./storage_service/docker-compose.yml
  - ./user_profile_service/docker-compose.yml

networks:
  backend:
    external: true