services:
  auth_service:
    build: .
    container_name: auth_service
    env_file:
      - ../.env
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - auth_db
    volumes:
      - ./auth_app/migrations:/app/auth_app/migrations
    networks:
      - backend

  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  auth_db_data:
