services:
  storage_service:
    build: .
    container_name: storage_service
    env_file:
      - ../.env
      - .env
    ports:
      - "8006:8000"
    depends_on:
      - storage_db
#    volumes:
#      - ./storage_app/migrations:/app/storage_app/migrations
    networks:
      - backend

  storage_db:
    image: postgres:15
    container_name: storage_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
#    volumes:
#      - storage_db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge