services:
  chat_service:
    build: .
    container_name: chat_service
    env_file:
      - ../.env
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - chat_redis
    networks:
      - backend

  chat_redis:
    image: redis
    container_name: chat_redis
    ports:
      - "6378:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
