# Generated by Django 5.1.7 on 2025-03-20 11:57

import config.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=config.s3_storage.MediaStorage(), upload_to=''),
        ),
    ]
