# Generated by Django 5.1.7 on 2025-03-20 12:53

import config.s3_storage
import storage_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=config.s3_storage.MediaStorage(), upload_to=storage_app.models.generate_unique_name),
        ),
    ]
