services:
  selection_deck_service:
    build: .
    container_name: selection_deck_service
    env_file:
      - ../.env
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - selection_deck_db
#    volumes:
#      - ./deck_app/migrations:/app/deck_app/migrations
    networks:
      - backend

  selection_deck_db:
    image: postgres:15
    container_name: selection_deck_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - selection_deck_db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  selection_deck_db_data: